[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "rm -f package-lock.json",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd backend",
  "npm run build"
]

[start]
cmd = "cd backend && node dist/server.js"