# .nixpacks.toml - Railway Build Configuration

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"
